cam0:
  Kl: [458.654, 457.296, 367.215, 248.375]
  Kr: [457.587, 456.134, 379.999, 255.238]
  Dl: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]
  Dr: [-0.28368365,  0.07451284, -0.00010473, -3.55590700e-05]
  Rl: [0.9999663475300330, -0.001422739138722922, 0.008079580483432283, 0.001365741834644127, 0.9999741760894847, 0.007055629199258132, -0.008089410156878961, -0.007044357138835809, 0.9999424675829176]
  Rr: [0.9999633526194376, -0.003625811871560086, 0.007755443660172947, 0.003680398547259526, 0.9999684752771629, -0.007035845251224894, -0.007729688520722713, 0.007064130529506649, 0.9999451734846440]
  cam_bl: 0.110077842
  cam_height: 480
  cam_model: Pinhole
  cam_width: 752
  R: [  9.99997256e-01,   2.31206719e-03,   3.76008102e-04, 
	-2.31713572e-03,   9.99898049e-01,   1.40898358e-02,
	-3.43393121e-04,  -1.40906685e-02,   9.99900663e-01 ]
  t: [ -0.11007381,  0.00039912, -0.0008537 ]
images_subfolder_l: cam0/data/
images_subfolder_r: cam1/data/
